### ISSUE TITLE
emptystateView Size issue

### ISSUE THREAD

**Issue by iHamzaaK** [luispadron/UIEmptyState#1]
Can you please make a proper documentation of all the features. 
Secondly the size of empty state is filled to the screen. I have my custom header and footerView which are not working since emptystate is placed on top of it. Can you tell me how to make the emptyStateView fit to the tableView.

**Comment by luispadron** [comment]
Did you read the README file? The documentation is all [here](http://htmlpreview.github.io/?https://github.com/luispadron/UIEmptyState/blob/master/docs/index.html) 

As for header and footer view, those will not be visible when the empty view is present and that is the intended behavior. If you want me to take a closer look then please attach an example project.

**Comment by luispadron** [comment]
@kevinonik, I've had more time to look at this issue and see what you mean. I originally thought you were talking about a default nav bar and this is working fine for that. 
However any custom views will be covered by the empty state, BUT in version 0.5.0 (out now) you can be notified when the empty state view is presented, in this method you could then bring the subviews to the front.

Example:

```swift
// Inside your view controller, which conforms to UIEmptyStateDelegate

@IBOutlet var customNavBar: UIView!

func emptyStateViewDidShow(view: UIView) {
   // The view has been shown, we can now bring our custom nav view to the front
   self.view.bringSubview(toFront: customNavBar)
}

```

[Read the full notes here](https://github.com/luispadron/UIEmptyState/releases/tag/v0.5.0)
