### ISSUE TITLE
How to access subviews of the UIEmptyStateView?

### ISSUE THREAD

**Issue by burkaslarry** [luispadron/UIEmptyState#10]
I would like to ask the question as above. Given I have set the image is AlwaysTemplate.

**Comment by luispadron** [comment]
The image view is just a regular `UIImageView` as well as `UIImage`.
It's inside the `UIViewController+UIEmptyState.swift` file, which is an extension on the `UIViewController` class. 

Here an `emptyStateView` property is set and has a type of `UIView`.

So to access the members of the `UIEmptyStateView`, such as the `UIImageView` you're looking for, you just need to cast to a `UIEmptyStateView`.

Example:

```swift
// Inside a UIViewController
(self.emptyStateView as? UIEmptyStateView)?.imageView.tintColor = UIColor.blue
```

**Comment by burkaslarry** [comment]
great thanks mate . I have used your framework and got positive feedbacks about user experience.

**Comment by luispadron** [comment]
Awesome to hear!
