### ISSUE TITLE
incorrect button background color

### ISSUE THREAD

**Issue by dexcell** [luispadron/UIEmptyState#14]
Setting button background color has no effect,

See the compiled example taken from latest github code (no red button color):
<img width="302" alt="screen shot 2017-12-22 at 01 45 40" src="https://user-images.githubusercontent.com/41800/34270177-dd032b92-e6b9-11e7-9f25-ff7b34db3745.png">

**Comment by luispadron** [comment]
I believe this is a bug in the example project and not actually the library. I’ll take a look at it and see why it’s not showing up. 

Thanks for the report!

**Comment by dexcell** [comment]
Hi Luis, thanks for the response.

It would be nice to have `emptyStateButton` on data source, so we can customize button looks there. (or kind of willDisplayButton func)

**Comment by luispadron** [comment]
You can do this already, just conform to `UIEmptyStateDelegate.emptyStateViewWillShow`. Here you can downcast UIView to `UIEmptyStateView`, this allows access to all the subviews. 

I just haven’t updated the example project to use this method, which is probably why it’s not working correctly.

**Comment by luispadron** [comment]
Fixed in [latest commit](https://github.com/luispadron/UIEmptyState/commit/ea61f7b9cdaedff82729cafb8b71f5ca2f1013d4)!

**Comment by dexcell** [comment]
Awesome! thanks for the example, it's working as expected now.
