### ISSUE TITLE
UIEmptyState View Misalignment

### ISSUE THREAD

**Issue by im-jersh** [luispadron/UIEmptyState#17]
It appears that UIEmptyState assumes that the table/collection view take up the full view of the parent view controller. However, in a UI where this is not so, the empty state view is centered vertically and horizontally to the view controller's view rather than the specific table/collection view to which it is depicting the empty state for (which I would think should be expected behavior, similar to DZNEmptyDataSet). 

![simulator screen shot - iphone x - 2018-02-22 at 14 52 37](https://user-images.githubusercontent.com/4296435/36563662-7d8cd9d0-17e0-11e8-8efa-1ab170d6e361.png)

Putting the empty data view on the view that it is showing an empty state for would be most helpful, especially for views that contain multiple table/collection views such as the one shown above.

**Comment by luispadron** [comment]
Could you provide an example project where I can reproduce this?

**Comment by im-jersh** [comment]
here's is an example reproducing the issue [https://github.com/oriyentel/UIEmptyStateBugExample](url)
