### ISSUE TITLE
No member safeAreaLayoutGuide

### ISSUE THREAD

**Issue by farazq** [luispadron/UIEmptyState#3]
Hi Luis,

Getting this build error... Any suggestions?

<img width="1193" alt="screen shot 2017-09-08 at 10 26 22 am" src="https://user-images.githubusercontent.com/1648391/30216254-691de50e-9480-11e7-9ab2-64af0f6bfe0f.png">

**Comment by luispadron** [comment]
Hey, are you using the latest Xcode? Which would be Xcode 9 (beta). 

The newer version require the latest Xcode, as those are methods available there. 

If you'd like to use the library on an older version, please use [v0.8.3](https://github.com/luispadron/UIEmptyState/releases/tag/v0.8.3). But I highly recommend just updating as the newer versions have fixed a lot of issues.

**Comment by farazq** [comment]
Actually I'm using Xcode 8. Will upgrade to 9. Thanks!
